### ISSUE TITLE
Display error screen when webview cannot be loaded (no internet, etc)

### ISSUE THREAD

**Issue by 0xean** [shapeshift/mobile-app#21]
# AC
- when webview is unable to load, display error screen to user with additional info if possible (no internet connection, etc)

**Comment by reallybeard** [comment]
![no-connection (1)](https://user-images.githubusercontent.com/89934888/184242302-bafb1f4f-aad0-4e8c-96f9-c36430a6aa88.png)

**Comment by reallybeard** [comment]
@0xean here is the mock for it, lmk when you need to get it built.

**Comment by 0xean** [comment]
thanks @reallybeard! Sorry for the slow response, just saw this today. Appreciate your willingness to build out the component in React Native as well. I think you should have access to this repo since its public, but let me know if there is anything else you need from us to get started.

**Comment by reallybeard** [comment]
Have the code ready just need write access to the repo so I can post a PR @0xean

**Comment by 0xean** [comment]
@reallybeard this should be resolved, can you try again
