### ISSUE TITLE
Balance charts not loading in mobile app

### ISSUE THREAD

**Issue by 0xean** [shapeshift/mobile-app#26]

**Comment by asamere** [comment]
As @0xean mentioned in DMs yesterday, charts now appear to be working just fine. It might be worth spinning up a fresh simulator in the off chance it's a "first load/until cached" issue.

**Comment by asamere** [comment]
@cjthompson PR https://github.com/shapeshift/mobile-app/pull/28 forwards console logs from the webview to the app's console. this will be a huge help debugging similar issues to this one.

**Comment by 0xean** [comment]
closing for now, @asamere will double check on another sim version
