### ISSUE TITLE
[Web] Welcome Modal UI for existing mobile users

### ISSUE THREAD

**Issue by willyogo** [shapeshift/mobile-app#39]
When an existing native wallet user opens the new mobile app for the first time and their seed is automatically imported, we want to display a custom Welcome Modal on the Dashboard to notify them that their wallet has been successfully imported to the new app and to prompt them to backup their wallet if they haven't already.

This ticket is just to add the Modal UI. A separate ticket will be created to trigger the modal.

![image](https://user-images.githubusercontent.com/26232238/186251062-44912464-e070-42f2-a774-bd28f563e86d.png)

AC:
1. Modal UI is added to web and matches mockup
2. If a user taps 'Get Secret Recovery Phrase' they are routed to the [Verify backup flow](https://www.figma.com/proto/eSaTFovDi9Re3ELrK2npkt/Back-Up-Wallet?node-id=1501%3A5630&scaling=min-zoom&page-id=1501%3A5628), which is already live in production and added in this [PR](https://github.com/shapeshift/web/issues/2427)
3. A flag is added to the verify backup flow to prevent users who come from the Welcome Modal from exiting out
4. If a user taps 'I already know my secret recovery phrase' the modal closes and the user sees their Dashboard

**Comment by reallybeard** [comment]
https://github.com/shapeshift/web/pull/2572
