### ISSUE TITLE
Copy Receive address results in an error message

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/mobile-app#51]
1. Connect a wallet (in this case I was testing Native wallet)
2. Navigate to an asset
3. Tap "Receive" 
4. Tap the icon to copy the receive address. Note the error that's displayed. 

Tested this on Android. Cross-tested against the website on mobile, the website is fine. This appears to only be an issue inside the app itself. I was able to get this error across multiple assets: ATOM, BTC, etc

![Screen Shot 2022-09-08 at 3 06 09 PM](https://user-images.githubusercontent.com/90058616/189225890-980decf9-8409-40ce-9daa-87db126faf11.png)

**Comment by 0xean** [comment]
this works on IOS
