### ISSUE TITLE
Create Wallet flow is broken with latest update 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/mobile-app#64]
With the latest merge (https://github.com/shapeshift/web/pull/2788/files) we appear to have broken the create wallet flow

https://github.com/shapeshift/web/blob/c06e143c432ca39bd13c13c41212466980a07bb1/src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx#L73

To recreate - 

1. Connect Wallet
2. Create 
3. Observe crash 
![image](https://user-images.githubusercontent.com/15096737/191743323-80ed4173-c186-49dd-90fe-41f1ec20a3b1.png)

I attempted to get the mobile app running locally pointed at a localhost version of the web app running but wasn't able to do this in order to debug.

**Comment by DiggyDiggy2** [comment]
i am able to replicate this on android as well.
