### ISSUE TITLE
App must target Android 13 (API level 33) or higher

### ISSUE THREAD

**Issue by 0xean** [shapeshift/mobile-app#98]
- upgrade android app to target 33+
- confirm working in emulator, builds, no (new) errors in logs 
- depend on https://github.com/shapeshift/mobile-app/pull/97 being merged first

**Comment by gomesalexandre** [comment]
Update: 1 stood for 1 minute, not 1 week
<img width="449" alt="image" src="https://github.com/shapeshift/mobile-app/assets/17035424/ae0ba97b-c561-4210-8088-e4f43ab5c979">

**Comment by NeOMakinG** [comment]
I think we can also close this one due to the new release we've done
